---
title: "Aktuelle datasett for hjemmeoppgaven"
output: github_document
---

Her er noen lenker dere kan ta utgangspunkt i for å finne aktuelle datasett til hjemmeoppgaven deres. Listen er ikke uttømmende så det finnes sikkert mye bra som ikke er listet opp her også. Jeg har heller ikke brukt disse datasettene selv så dere må sette dere ned med kodebok og selv vurdere om de er relevante og av god nok kvalitet for din problemstilling. Vi begynner med instituttet og UB sine ressuser: 

- Dere finner mange datasett sortert på tema på [ISV sin side “Statistikk, datasett og ressuser på nett»](https://www.sv.uio.no/isv/tjenester/kunnskap/datasett/)
- [UB sin fagside med lenker til noen datasett (se nederst)](https://www.ub.uio.no/fag/samfunn-politikk/statsvit/)

Noen eksempler (mulig disse også er lenket til via ISV sin side): 

- [The Nonviolent and Violent Campaigns and Outcomes (NAVCO) Data Project](https://www.du.edu/korbel/sie/research/chenow_navco_data.html)
- [Varities of democracy](https://www.v-dem.net/en/)
- [Data on armed conflict fra PRIO](https://www.prio.org/Data/Armed-Conflict/)
- [European social survey](https://www.europeansocialsurvey.org/) 
- [Quality of government](https://www.gu.se/en/quality-government/qog-data) 
- [Afrobarometro](https://www.afrobarometer.org/)
- [Latinobarómetro](https://www.latinobarometro.org/lat.jsp)
- [Political party database project (PPDB)](https://www.politicalpartydb.org/)
- [Parliaments and government database (PARLGOV)](http://www.parlgov.org/)

For replikasjonsdata: 

- Søk etter tema eller artikkel på [Harvard dataverse](https://dataverse.harvard.edu/)
- Sjekk også tidsskriftet artikkelen er publisert i
- Sjekk fotnoter i artikkelen om det står noe om hvor data er gjort tilgjenglig
- Ikke alle legger ut repliksjonsdata desverre 